In [1]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [2]:
tf.constant(100)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [3]:
tensor_a = tf.constant(100) # 상수텐서 
print(tensor_a)
tensor_a.numpy() # 출력하기

tf.Tensor(100, shape=(), dtype=int32)


100

In [7]:
tensor_b = tf.constant(3)
tensor_c = tf.constant(2)

tensor_d = tf.add(tensor_b,tensor_c)
print(tensor_d.numpy())


5


In [9]:
tensor_e = tf.multiply(tensor_b,tensor_c)
print(tensor_e.numpy())

6


In [10]:
tensor_f = tensor_b - tensor_c # 계산기호사용가능
print(tensor_f.numpy())

1


In [13]:
tensor_ma = tf.constant([[1,2],[3,4]])
tensor_mb = tf.constant([[2,0],[0,2]])
tensor_mc = tensor_ma * tensor_mb #벡터 곱하기
print(tensor_mc.numpy())
tensor_md = tf.matmul(tensor_ma,tensor_mb) #메트릭스 곱 
print(tensor_md.numpy())

[[2 0]
 [0 8]]
[[2 4]
 [6 8]]
